### ISSUE TITLE
routes directory is missing

### ISSUE THREAD

**Issue by yonida** [flatlogic/react-dashboard#1]
in `router.js` you import `routes` but it is missing in the project:  
https://github.com/flatlogic/react-dashboard/blob/master/src/router.js#L11
The missing directory exists in `react-starter-kit`:
https://github.com/kriasoft/react-starter-kit/tree/master/src/routes

**Comment by DimaSavchenko** [comment]
Hi, @yonida ! 
This file is unused. We change 'universal-router' from react-starter-kit to 'react-router'.
I have remove this file.
Thanks!
