### ISSUE TITLE
Command: node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by novasush** [flatlogic/react-dashboard#15]
Arguments: 
Directory: /home/sush/Instafashion_Admin/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.15.2 | linux | x64
node-pre-gyp info check checked for "/home/sush/Instafashion_Admin/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.15.2 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.15.2 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file

**Comment by mariesta** [comment]
I got the same error message when running `yarn install`.

**Comment by novasush** [comment]
> I got the same error message when running `yarn install`.
> 
> Possible workaround: Running `yarn add sqlite3` fixes the issue for me.

There were more bugs when i started developing on later stage, so i just switched to creativetim's react dashboard. 😄
