### ISSUE TITLE
unable to install 'yarn install'

### ISSUE THREAD

**Issue by fortydegrees** [flatlogic/react-dashboard#17]
so first off i get:

> yarn install v1.15.2
> [1/5] 🔍  Validating package.json...
> error web@0.0.0: The engine "node" is incompatible with this module. Expected version "8.10.0". Got "11.15.0"
> error Found incompatible module
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

kinda odd, but no major worries, i just change package.json and continue. and then i start getting the mother of all errors:

> warning Error running install script for optional dependency: "/dashboard/node_modules/fsevents: Command failed.
> Exit code: 1
> Command: node install
> Arguments: 
> Directory: /dashboard/node_modules/fsevents
> Output:
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.6.36
> node-pre-gyp info using node@11.15.0 | darwin | x64
> node-pre-gyp info check checked for \"/dashboard/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node\" (not found)
> node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz
> node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz
> node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v67-darwin-x64.tar.gz 

another output: 'Failed to execute '/Users/david/.nvm/versions/node/v11.15.0/bin/node /Users/david/ballpark/dashboard/node_modules/node-gyp/bin/node-gyp'

the final output is: 'gyp ERR! cwd /Users/david/ballpark/dashboard/node_modules/sqlite3'

then i get a ton of 'gyp info spawn args' output in the terminal. i've tried with npm and different versions of node, but no luck. really not sure how to get around with this one - obviously not convinced it's an error with this project but wondering if anyone might know a solution?

**Comment by fortydegrees** [comment]
I return sheepishly with a solution. Obviously it is to use the version of node specified in the config.

> nvm install 8.10.0

got me a working install. Leaving this here as I reckon a few others might have this issue.

**Comment by michaeldaineka** [comment]
Hi there! Thanks for feedback!

We pushed a new commit that contains the problem. 

Best regards!
