### ISSUE TITLE
Any way to make this static?

### ISSUE THREAD

**Issue by nachoargentina** [flatlogic/react-dashboard#4]
Hi guys, love the work you have done with the dashboard and how everything is organized and well explained.
I was actually wondering how to modify this project so that it uses the good-old index.html/js approach to be able to easily deploy it as a static page. I know this might involve heavy modification of webpack config file (in which I'm still no expert). I tried some changes but I can't make it like that yet.
I won't ask you guys if you can do it, but rather if you have any advice that can point me in the right direction on how to achive this (or maybe something like "don't even bother, the way this is structured, it can't be done).
Anyway, any advice would be much appretiated!
Thanks in advance for your time

**Comment by kujaomega** [comment]
Nice work guys. Making static files, will be great to separate client and server

**Comment by highthem** [comment]
`yarn build --static` will do the job! your will get a `build` folder as output with your index.html file.

**Comment by michaeldaineka** [comment]
Hi there! Thanks for curious!

Enter
```
yarn build --production
```

Best regards!
